& "$PSScriptRoot\10-core.ps1"
& "$PSScriptRoot\20-languages.ps1"
& "$PSScriptRoot\30-editors.ps1"
& "$PSScriptRoot\40-shell.ps1"
& "$PSScriptRoot\50-cli-tools.ps1"
& "$PSScriptRoot\60-config-links.ps1"
